### ISSUE TITLE
Arch Package: ModuleNotFoundError: No module named 'packaging.version'

### ISSUE THREAD

**Issue by dethredic** [sezanzeb/input-remapper#671]
```
08:30:40.778805 98115 GUI DEBUG logger.py:296: Using rich.traceback
08:30:40.778890 98115 GUI INFO logger.py:264: input-remapper-gtk 2.0.0 7c561dde89bfdb7f9978201f84edb7b9e2e46300 https://github.com/sezanzeb/input-remapper
08:30:40.778973 98115 GUI INFO logger.py:272: python-evdev 1.6.1
08:30:40.779021 98115 GUI WARNING logger.py:275: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
08:30:40.779065 98115 GUI DEBUG input-remapper-gtk:67: Using locale directory: /usr/share/input-remapper/lang
08:30:40.791887 98115 GUI DEBUG pipe.py:70: Creating new pipe for "/tmp/input-remapper-phil/reader-results"
08:30:40.793547 98115 GUI DEBUG pipe.py:70: Creating new pipe for "/tmp/input-remapper-phil/reader-commands"
08:30:40.794277 98115 GUI DEBUG message_broker.py:97: adding new Listener for MessageType.terminate: <function ReaderClient.attach_to_events.<locals>.<lambda> at 0x7fb2685a4310>
08:30:40.794527 98115 GUI DEBUG reader_service.py:144: Running `pkexec input-remapper-control --command start-reader-service -d`
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 30, in <module>
    from inputremapper.logger import logger, update_verbosity, log_info
  File "/usr/lib/python3.10/site-packages/inputremapper/logger.py", line 29, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 91, in <module>
    __import__('packaging.version')
ModuleNotFoundError: No module named 'packaging.version'
08:30:43.467538 98115 GUI ERROR input-remapper-gtk:50: Failed to pkexec the reader-service, code 256
```

```
$ input-remapper-control --version
input-remapper 2.0.0 7c561dde89bfdb7f9978201f84edb7b9e2e46300 https://github.com/sezanzeb/input-remapper
python-evdev 1.6.1
```

I've been using this package successfully for 6 months, but this started happening a day or two ago. I tried re-installing the package with yay with no luck

**Comment by sezanzeb** [comment]
fixed in the most recent commit

**Comment by dethredic** [comment]
I installed the latest version and this issue persists in another file:
```
Package (1)         Old Version           New Version           Net Change

input-remapper-git  2.0.0.r1.g7c561dde-1  2.0.0.r3.g190da9de-1    0.00 MiB

Total Installed Size:  1.13 MiB
Net Upgrade Size:      0.00 MiB
```

```
08:23:30.756757 19778 GUI DEBUG logger.py:297: Using rich.traceback
08:23:30.756807 19778 GUI INFO logger.py:265: input-remapper-gtk 2.0.0 190da9de381485a462a87b254caf320280a94d86 https://github.com/sezanzeb/input-remapper
08:23:30.756849 19778 GUI INFO logger.py:273: python-evdev 1.6.1
08:23:30.756869 19778 GUI WARNING logger.py:276: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
08:23:30.756887 19778 GUI DEBUG input-remapper-gtk:67: Using locale directory: /usr/share/input-remapper/lang
08:23:30.763404 19778 GUI DEBUG pipe.py:70: Creating new pipe for "/tmp/input-remapper-phil/reader-results"
08:23:30.764286 19778 GUI DEBUG pipe.py:70: Creating new pipe for "/tmp/input-remapper-phil/reader-commands"
08:23:30.764717 19778 GUI DEBUG message_broker.py:97: adding new Listener for MessageType.terminate: <function ReaderClient.attach_to_events.<locals>.<lambda> at 0x7f1affab8310>
08:23:30.764858 19778 GUI DEBUG reader_service.py:144: Running `pkexec input-remapper-control --command start-reader-service -d`
Could not figure out the version
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 31, in <module>
    from inputremapper.configs.migrations import migrate
  File "/usr/lib/python3.10/site-packages/inputremapper/configs/migrations.py", line 35, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 91, in <module>
    __import__('packaging.version')
ModuleNotFoundError: No module named 'packaging.version'
08:23:33.547324 19778 GUI ERROR input-remapper-gtk:50: Failed to pkexec the reader-service, code 256
```

**Comment by dethredic** [comment]
Yes, that fixes it for me! The pacakge dependancies should get updated I guess

**Comment by sezanzeb** [comment]
yes, thanks. I have added it to the AUR package and the DEBIAN/control file
